Added all Sort commands
AY2223S1-CS2103T-W08-1/tp pull request #116
Opened 2022-10-18 15:37 UTC by SpecOps2016

2022-10-18 15:41 UTC, Fuzanwenn approved these changes
LGTM!

2022-10-18 16:12 UTC, TZL0 approved these changes
LGTM

2022-10-18 16:13 UTC, TZL0 requested changes

2022-10-18 16:13 UTC, TZL0 commented on src/main/java/seedu/address/Main.java
> + *     Error: JavaFX runtime com.ponents are missing, and are required to run this application
Wrong spelling?

2022-10-19 00:41 UTC, SpecOps2016 commented on src/main/java/seedu/address/Main.java
> + *     Error: JavaFX runtime com.ponents are missing, and are required to run this application
Resolved

2022-10-19 04:58 UTC, TZL0 approved these changes

2022-10-19 04:59 UTC, merged