Find bill optimised
AY2223S1-CS2103T-W08-1/tp pull request #158
Opened 2022-10-26 11:56 UTC by wadia82

2022-10-26 12:28 UTC, SpecOps2016 approved these changes
Code quality looks good. Code is neat and succinct. Good work!

2022-10-26 12:28 UTC, SpecOps2016 commented on src/main/java/seedu/address/logic/commands/FindBillCommand.java
> +    /**
Nice use of JavaDocs

2022-10-26 13:53 UTC, guokweijie commented on src/main/java/seedu/address/logic/commands/FindBillCommand.java
> +    public FindBillCommand(Optional<Predicate<Name>> namePredicate,
what about find by bill date and amount?

2022-10-27 00:13 UTC, guokweijie requested changes

2022-10-27 00:13 UTC, guokweijie commented on src/main/java/seedu/address/logic/parser/FindBillCommandParser.java
> +            this.amountPredicate = (amount -> amount.toString().equals(trimmedArgs));
use contains instead of equals, can check regex using ^[0-9.]+$ which only allows for numbers and decimal point .

2022-10-27 10:00 UTC, guokweijie requested changes

2022-10-27 13:31 UTC, SpecOps2016 commented on src/main/java/seedu/address/logic/commands/FindBillCommand.java
>              + " numbers.\n"
resolved

2022-10-27 13:32 UTC, merged