Add EditAppointment Tests
AY2223S1-CS2103T-W08-1/tp pull request #82
Opened 2022-10-10 17:07 UTC by Fuzanwenn

2022-10-10 17:21 UTC, TZL0 requested changes

2022-10-10 17:21 UTC, TZL0 commented on src/test/java/seedu/address/logic/parser/EditAppointmentCommandParserTest.java
> +        // phone
Is it possible to remove this part?

2022-10-10 17:21 UTC, TZL0 commented on src/test/java/seedu/address/logic/parser/EditAppointmentCommandParserTest.java
> +        userInput = targetIndex.getOneBased() + SLOT_DESC_7;
Is it slot?

2022-10-10 17:21 UTC, TZL0 commented on src/test/java/seedu/address/logic/parser/EditAppointmentCommandParserTest.java
> +        // address
Is it medical test?

2022-10-10 17:21 UTC, TZL0 commented on src/test/java/seedu/address/logic/parser/EditAppointmentCommandParserTest.java
> +        // email
Is it doctor?

2022-10-10 17:21 UTC, TZL0 commented on src/test/java/seedu/address/testutil/EditAppointmentDescriptorBuilder.java
> +     * Returns an {@code EditPersonDescriptor} with fields containing {@code person}'s details
EditAppointmentDescriptor?

2022-10-10 17:25 UTC, TZL0 approved these changes

2022-10-11 05:40 UTC, SpecOps2016 approved these changes
LGTM

2022-10-11 06:02 UTC, merged